php_to_type_script:
  indentation: 4
  inputDirectory: src
  outputDirectory: libs/shared/domain/src/interfaces/
  prefix: I
  nullable: true

#  interfaces:
#    # Product Tile
#    'src/Model/ProductTile.php':
#      output: Model/
