name: Build 🚀

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  main:
    name: Main Workflow
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: lint,build,test
